/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "exam-mlc-city-weather": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "exam-mlc-city-weather-bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "exam-mlc-city-weather-history": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "exam-mlc-city-weather-history-bucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
